name: Tag
on:
  push:
    branches:
      - master # Default release branch
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Tag
        id: tag
        uses: simpleactions/create-tag@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: v4.0.1
          message: 4.0.1
